//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace VSTSStatusMonitor.UI
{
    public static class MyImageIds
    {
        public static readonly Guid MonikersGuid = new Guid("{ef144e7d-307f-4ad5-8de7-865f7deb3f6d}");

        public const int Artifacts = 0;
        public const int Boards = 1;
        public const int CoreServices = 2;
        public const int Repos = 3;
        public const int TestPlans = 4;
        public const int Pipelines = 5;
    }
}
