// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTSStatusMonitor
{
    static class Vsix
    {
        public const string Id = "beb913a8-333c-41b1-a736-878cebad3bc6";
        public const string Name = "VSTS Status Monitor";
        public const string Description = @"Monitor status of Visual Studio Team Services inside Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "Utkarsh Shigihalli and Tarun Arora";
        public const string Tags = "VSTS, Visual Studio Team Service, Monitor, Status, Inspector";
    }
}
