//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace AzureDevOpsStatusMonitor
{
    public static class MyImageIds
    {
        public static readonly Guid MonikersGuid = new Guid("{ef144e7d-307f-4ad5-8de7-865f7deb3f6d}");

        public const int Advisory = 11;
        public const int Artifacts = 12;
        public const int Boards = 13;
        public const int CoreServices = 14;
        public const int Degraded = 15;
        public const int Healthy = 16;
        public const int Pipelines = 17;
        public const int Repos = 18;
        public const int TestPlans = 19;
        public const int Unhealthy = 10;
    }
}
