//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using Microsoft.VisualStudio.Imaging.Interop;

namespace AzureDevOpsStatusMonitor
{
    public static class MyMonikers
    {
        public static ImageMoniker Advisory { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Advisory }; } }
        public static ImageMoniker Artifacts { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Artifacts }; } }
        public static ImageMoniker Boards { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Boards }; } }
        public static ImageMoniker CoreServices { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.CoreServices }; } }
        public static ImageMoniker Degraded { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Degraded }; } }
        public static ImageMoniker Healthy { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Healthy }; } }
        public static ImageMoniker Pipelines { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Pipelines }; } }
        public static ImageMoniker Repos { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Repos }; } }
        public static ImageMoniker TestPlans { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.TestPlans }; } }
        public static ImageMoniker Unhealthy { get { return new ImageMoniker { Guid = MyImageIds.MonikersGuid, Id = MyImageIds.Unhealthy }; } }
    }
}
